language: python

python:
  - "3.7-dev"

stages:
  - cassius
  - test
  - end

jobs:
  include:
    - script: pytest
    - stage: cassius

    - script: pytest
    - stage: test

    - script: echo 'Done'
    - stage: end
