language: python

python:
  - "3.7-dev"

stages:
  - pre-test
  - test
  - end

jobs:
  include:
    - stage: pre-test
      name: 'Pre testing'
      script: echo 'Preparing for test'

    - stage: test
      name: 'Test'
      script: pytest

    - stage: deploy
      name: 'Deploy'
      script: echo 'Deploying...'
